# Generated by Django 6.0.3 on 2026-03-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frase',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
