# Generated by Django 6.0.3 on 2026-03-21 02:25

import prhases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_esp', models.TextField()),
                ('texto_jp', models.TextField()),
                ('nota', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoría', models.ForeignKey(on_delete=models.SET(prhases.models.crear_sin_categoria), related_name='Frases', to='prhases.categoria')),
            ],
        ),
    ]
